#' Heat map with hierarchical clustering 
#'
#' Plots a heat map including dendrograms generated by hierarchical clustering
#' for the data given via the argument "input.path" and writes it to a pdf file
#' in the same location. 
#' @param input.path Path to a tab-separated txt file (note: path needs to be in
#' Linux style, i.e. "/" instead of "\"). 
#' @return The desired heat map with hierarchical clustering exported
#' to a pdf file in "input.path". 
#' @examples 
#' plotHeatClust("path/to/your/data-file.txt")
#' @export
plotHeatClust <- function(input.path=NULL){
  
  dat <- read.table(input.path, header=T, sep="\t")
  rownames(dat) <- dat[,1]
  dat <- as.matrix(dat[,-1])

  
  
  group.names <- unique(gsub("^(.+)\\_.+$", "\\1", colnames(dat)))
  groups <- list()
  for(i in 1:length(group.names)){
    pattern <- paste0("^",group.names[i],"_")
    groups[[group.names[i]]] <- grep(pattern, colnames(dat))
  }

  
  
  p.val <- vector(mode="numeric", length=nrow(dat))
  max.fc <- vector(mode="numeric", length=nrow(dat))
  for(i in 1:nrow(dat)){
      p.val[i] <- t.test(dat[i,groups[[1]]], dat[i,groups[[2]]])$p.value
      
      fc1 <- mean(dat[i,groups[[1]]]) / mean(dat[i,groups[[2]]])
      fc2 <- mean(dat[i,groups[[2]]]) / mean(dat[i,groups[[1]]])
      max.fc[i] <- max(fc1, fc2) 
  }
  fdr <- p.adjust(p=p.val, method="fdr")
  
  diff.idx1 <- which(fdr < 0.0001)
  diff.idx2 <- which(max.fc > 2.5)
  diff.idx <- intersect(diff.idx1, diff.idx2)
  print(diff.idx)
  
  
  #my.dist <- dist
  my.dist <- function(x) as.dist(1-cor(t(x), method="spearman"))
  #"euclidean", "maximum", "manhattan", "canberra", "binary" or "minkowski"
  my.hclust <- function(d) hclust(d, method="complete")
  #"ward", "single", "complete", "average", "mcquitty",
  #"median" or "centroid"
  heatmap.2(dat[diff.idx,],
            distfun=my.dist,
            hclustfun=my.hclust,
            scale="row",
            trace="none")
  
  output.path <- gsub("^(.+)\\/.+\\.txt$","\\1",input.path)
  pdf(file=paste0(output.path, "/plotHeatClust-output.pdf"))
      heatmap.2(dat[diff.idx,],
                distfun=my.dist,
                hclustfun=my.hclust,
                scale="row",
                trace="none")
  dev.off()
}

#plotHeatClust(input.path="E:/Projekte/icbToolbox/data/hcc.txt")
